spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  bot-token: 666231685:AAGKQhsNyUg_0xz996jRc2KE3wdB6epeHec
  jwt-secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#
#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.security.access.expression.method: DEBUG
